#better feature engineering


In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.decomposition import PCA

#import pytorch

In [2]:
df_train= pd.read_csv('./Accident_train.csv')
df_test=pd.read_csv('./Accident_test.csv')

In [3]:
df_train.head()

Collision_Ref_No Policing_Area  Collision_Severity Weekday_of_Collision  \
0              3518          CREA                   3                  MON   
1             10557          BELC                   3                  SAT   
2              5002          LISB                   3                  WED   
3             11714          BELC                   3                  SUN   
4             12416          MIDU                   3                  MON   

   Day_of_Collision  Month_of_Collision  Hour_of_Collision  Carriageway_Type  \
0                 4                   8               14.0                13   
1                 8                   8               17.0                11   
2                 5                  11               17.0                 1   
3                18                  10               16.0                12   
4                23                  11                9.0                13   

   Speed_Limit  Junction_Detail  Junction_Control  Ped_Crossing_HC  \
0           60              1.0               1.0              1.0   
1           50             12.0               7.0              1.0   
2           60             12.0               7.0              1.0   
3           70              6.0               NaN              1.0   
4           60              6.0               7.0              1.0   

   Ped_Crossing_PC  Light_Conditions  Weather_Conditions  \
0              1.0                 2                   9   
1              1.0                 4                   3   
2              1.0                 2                   2   
3              1.0                 1                   3   
4              1.0                 2                   3   

   Road_Surface_Conditions  Special_Conditions_at_Site  
0                      9.0                         1.0  
1                      1.0                         1.0  
2                      2.0                         1.0  
3                      1.0                         1.0  
4                      1.0                         1.0

In [4]:
df_train.describe()

Collision_Ref_No  Collision_Severity  Day_of_Collision  \
count      10043.000000        10043.000000      10043.000000   
mean        6565.855720            2.880613         15.662153   
std         3928.749772            0.359226          8.783339   
min            1.000000            1.000000          1.000000   
25%         3060.500000            3.000000          8.000000   
50%         7009.000000            3.000000         16.000000   
75%        10078.500000            3.000000         23.000000   
max        13147.000000            3.000000         31.000000   

       Month_of_Collision  Hour_of_Collision  Carriageway_Type   Speed_Limit  \
count        10043.000000        9759.000000      10043.000000  10043.000000   
mean             6.655382          13.624859         12.201036     42.415613   
std              3.526781           5.099759          2.744209     14.524589   
min              1.000000           0.000000          1.000000     10.000000   
25%              4.000000          10.000000         13.000000     30.000000   
50%              7.000000          14.000000         13.000000     30.000000   
75%             10.000000          17.000000         13.000000     60.000000   
max             12.000000          23.000000         14.000000     70.000000   

       Junction_Detail  Junction_Control  Ped_Crossing_HC  Ped_Crossing_PC  \
count      9750.000000       9744.000000      9722.000000      9743.000000   
mean          6.400410          4.158764         1.007714         2.231243   
std           5.016853          2.864940         0.114938         3.252212   
min           1.000000          1.000000         1.000000         1.000000   
25%           1.000000          1.000000         1.000000         1.000000   
50%           6.000000          4.000000         1.000000         1.000000   
75%          12.000000          7.000000         1.000000         1.000000   
max          12.000000          7.000000         3.000000        12.000000   

       Light_Conditions  Weather_Conditions  Road_Surface_Conditions  \
count      10043.000000        10043.000000              9734.000000   
mean           3.237778            4.717216                 1.661804   
std            2.067334            3.745739                 1.470371   
min            1.000000            1.000000                 1.000000   
25%            1.000000            1.000000                 1.000000   
50%            3.000000            3.000000                 1.000000   
75%            5.000000            9.000000                 2.000000   
max            7.000000           10.000000                10.000000   

       Special_Conditions_at_Site  
count                 9755.000000  
mean                     1.057099  
std                      0.480414  
min                      1.000000  
25%                      1.000000  
50%                      1.000000  
75%                      1.000000  
max                      6.000000

In [5]:
#print(df_train['Junction_Control'].unique())
#print(pd.value_counts(df_train['Junction_Control'].values))
#print(pd.value_counts(df_train['Ped_Crossing_HC'].values))
#print(pd.value_counts(df_train['Policing_Area'].values))
#print(pd.value_counts(df_train['Collision_Severity'].values))

In [6]:
# special conditions at site has 75% as 1 so replacing with mode.
df_train['Special_Conditions_at_Site'].fillna(1,inplace=True)
df_test['Special_Conditions_at_Site'].fillna(1,inplace=True)

# junction replacing with 6 (cross roads)
df_train['Junction_Detail'].fillna(6,inplace=True)
df_test['Junction_Detail'].fillna(6,inplace=True)

#Junction controlrandomly fill 1 or 7
df_train['Junction_Control'].fillna(np.random.choice([1,7]),inplace=True)
df_test['Junction_Control'].fillna(np.random.choice([1,7]),inplace=True)

#pedcrossing by 1
df_train['Ped_Crossing_HC'].fillna(1,inplace=True)
df_train['Ped_Crossing_PC'].fillna(1,inplace=True)
df_test['Ped_Crossing_HC'].fillna(1,inplace=True)
df_test['Ped_Crossing_PC'].fillna(1,inplace=True)

#road surface 1,2
df_train['Road_Surface_Conditions'].fillna(np.random.choice([1,7]),inplace=True)
df_test['Road_Surface_Conditions'].fillna(np.random.choice([1,7]),inplace=True)

#hour of collsion  random between 12 to 19
df_train['Hour_of_Collision'].fillna(np.random.randint(12,19),inplace=True)
df_test['Hour_of_Collision'].fillna(np.random.randint(12,19),inplace=True)

# Policing areas 
df_train['Policing_Area'].fillna(np.random.choice(['BELC','ARBC','NEMD','LISC','LISB']),inplace=True)
df_test['Policing_Area'].fillna(np.random.choice(['BELC','ARBC','NEMD','LISC','LISB']),inplace=True)


nan_rows = df_train[df_train.isnull().T.any().T]
nan_rows

Empty DataFrame
Columns: [Collision_Ref_No, Policing_Area, Collision_Severity, Weekday_of_Collision, Day_of_Collision, Month_of_Collision, Hour_of_Collision, Carriageway_Type, Speed_Limit, Junction_Detail, Junction_Control, Ped_Crossing_HC, Ped_Crossing_PC, Light_Conditions, Weather_Conditions, Road_Surface_Conditions, Special_Conditions_at_Site]
Index: []

In [7]:
nan_rows = df_test[df_test.isnull().T.any().T]
nan_rows

Empty DataFrame
Columns: [Collision_Ref_No, Policing_Area, Collision_Severity, Weekday_of_Collision, Day_of_Collision, Month_of_Collision, Hour_of_Collision, Carriageway_Type, Speed_Limit, Junction_Detail, Junction_Control, Ped_Crossing_HC, Ped_Crossing_PC, Light_Conditions, Weather_Conditions, Road_Surface_Conditions, Special_Conditions_at_Site]
Index: []

In [8]:
df_train=df_train.drop(['Collision_Ref_No'],axis=1)
df_train=df_train.drop(['Policing_Area'],axis=1)
df_test=df_test.drop(['Collision_Ref_No'],axis=1)
df_test=df_test.drop(['Policing_Area'],axis=1)

In [9]:
#onehot_pa=pd.get_dummies(df_train['Policing_Area'])
#onehot_week=pd.get_dummies(df_train['Weekday_of_Collision'])
#
#df_train=pd.concat([df_train,onehot_week],axis=1)#onehot_pa,
#
#onehot_week=pd.get_dummies(df_test['Weekday_of_Collision'])
#
#df_test=pd.concat([df_test,onehot_week],axis=1)#onehot_pa,

df_train=df_train.replace({'Weekday_of_Collision' : { 'MON' : 0, 'TUE' : 0, 'WED' : 0,'THU':0,'FRI':0,'SAT':1,'SUN':1 }})
df_test=df_test.replace({'Weekday_of_Collision' : { 'MON' : 0, 'TUE' : 0, 'WED' :0,'THU':0,'FRI':0,'SAT':1,'SUN':1 }})

#df_train

In [10]:
#df_train=df_train.drop(['Weekday_of_Collision'],axis=1)#'Policing_Area',
#df_test=df_test.drop(['Weekday_of_Collision'],axis=1)#'Policing_Area',

df_train=df_train.drop(['Ped_Crossing_HC','Special_Conditions_at_Site','Road_Surface_Conditions','Weekday_of_Collision','Day_of_Collision','Month_of_Collision'],axis=1)#'Policing_Area',
df_test=df_test.drop(['Ped_Crossing_HC','Special_Conditions_at_Site','Road_Surface_Conditions','Weekday_of_Collision','Day_of_Collision','Month_of_Collision'],axis=1)#'Policing_Area',


In [11]:
df_train.describe()

Collision_Severity  Hour_of_Collision  Carriageway_Type   Speed_Limit  \
count        10043.000000       10043.000000      10043.000000  10043.000000   
mean             2.880613          13.720303         12.201036     42.415613   
std              0.359226           5.058169          2.744209     14.524589   
min              1.000000           0.000000          1.000000     10.000000   
25%              3.000000          10.000000         13.000000     30.000000   
50%              3.000000          14.000000         13.000000     30.000000   
75%              3.000000          17.000000         13.000000     60.000000   
max              3.000000          23.000000         14.000000     70.000000   

       Junction_Detail  Junction_Control  Ped_Crossing_PC  Light_Conditions  \
count     10043.000000      10043.000000     10043.000000      10043.000000   
mean          6.388728          4.243354         2.194464          3.237778   
std           4.943581          2.862988         3.210115          2.067334   
min           1.000000          1.000000         1.000000          1.000000   
25%           1.000000          1.000000         1.000000          1.000000   
50%           6.000000          7.000000         1.000000          3.000000   
75%          12.000000          7.000000         1.000000          5.000000   
max          12.000000          7.000000        12.000000          7.000000   

       Weather_Conditions  
count        10043.000000  
mean             4.717216  
std              3.745739  
min              1.000000  
25%              1.000000  
50%              3.000000  
75%              9.000000  
max             10.000000

In [12]:
#df_train=df_train.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
#df_test=df_test.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [13]:
df_train_y=df_train['Collision_Severity']
df_train=df_train.drop(['Collision_Severity'],axis=1)
df_test=df_test.drop(['Collision_Severity'],axis=1)
#df_train=df_train.drop(['Special_Conditions_at_Site'],axis=1)
#df_test=df_test.drop(['Special_Conditions_at_Site'],axis=1)

In [14]:
#df_train_y
#df_train[df_train['Collision_Severity']==1].describe()

In [15]:
df_train_y.describe()

count    10043.000000
mean         2.880613
std          0.359226
min          1.000000
25%          3.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: Collision_Severity, dtype: float64

In [17]:
print(pd.value_counts(df_train_y.values))
#X_train, X_test, y_train, y_test = train_test_split(df_train, df_train_y, test_size=0.4, random_state=1)

#print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)
#print(pd.value_counts(y_test.values))

3    8964
2     959
1     120
dtype: int64


In [18]:

clf = tree.DecisionTreeClassifier()
clf = clf.fit(df_train, df_train_y)
#ypredc=clf.predict(X_test)
#accuracy = accuracy_score(y_test,ypredc)
#print("Accuracy with no NAN and onehot")
#accuracy
sub2=clf.predict(df_test)
fil=open('sub_10feat.csv','w')
fil.write('S.No.,Collision_Severity\n')
for i in range(sub2.shape[0]-1):
    fil.write('%d,%d\n'%(i+1,sub2[i]))
fil.write('%d,%d'%(i+2,sub2[i+1]))
fil.close()

In [19]:
sub2

array([3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 2, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
       3, 3, 2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 1, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3,
       3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3,
       3, 1, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       1, 3,

In [22]:

clf = RandomForestClassifier(n_estimators=55)
clf = clf.fit(df_train, df_train_y)
#ypredc=clf.predict(X_test)
#accuracy = accuracy_score(y_test,ypredc)
#accuracy
sub2=clf.predict(df_test)
fil=open('sub_10feat_RF.csv','w')
fil.write('S.No.,Collision_Severity\n')
for i in range(sub2.shape[0]-1):
    fil.write('%d,%d\n'%(i+1,sub2[i]))
fil.write('%d,%d'%(i+2,sub2[i+1]))
fil.close()

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)
ypredc=clf.predict(X_test)
accuracy = accuracy_score(y_test,ypredc)
print(accuracy)
#0.904430064709

In [20]:

#final test accuracy  0.91194
#clf = GradientBoostingClassifier(n_estimators=20, learning_rate=0.5,max_depth=2, random_state=0) # no onehots
clf = GradientBoostingClassifier(n_estimators=1000, learning_rate=0.01,max_depth=3, random_state=1)
clf = clf.fit(df_train, df_train_y)
#ypredc=clf.predict(X_test)
#accuracy = accuracy_score(y_test,ypredc)
#accuracy
#0.90890990542558492
sub2=clf.predict(df_test)
fil=open('sub_10feat.csv','w')
fil.write('S.No.,Collision_Severity\n')
for i in range(sub2.shape[0]-1):
    fil.write('%d,%d\n'%(i+1,sub2[i]))
fil.write('%d,%d'%(i+2,sub2[i+1]))
fil.close()

In [24]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=1000,max_depth=9)
clf = clf.fit(df_train, df_train_y)
sub2=clf.predict(df_test)
fil=open('sub_10feat.csv','w')
fil.write('S.No.,Collision_Severity\n')
for i in range(sub2.shape[0]-1):
    fil.write('%d,%d\n'%(i+1,sub2[i]))
fil.write('%d,%d'%(i+2,sub2[i+1]))
fil.close()

In [ ]:
sub2=clf.predict(df_test)
fil=open('sub_10feat.csv','w')
fil.write('S.No.,Collision_Severity\n')
for i in range(sub2.shape[0]-1):
    fil.write('%d,%d\n'%(i+1,sub2[i]))
fil.write('%d,%d'%(i+2,sub2[i+1]))
fil.close()

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
clf = gnb.fit(X_train, y_train)
ypredc=clf.predict(X_test)
accuracy = accuracy_score(y_test,ypredc)
print("Accuracy with no NAN and onehot")
accuracy

## 

In [21]:
sub2

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3,

In [23]:
sub2

array([3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 2, 3, 3, 1, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 1, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3,
       3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       1, 3,

In [25]:
sub2

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3,